---
title: "Heart Disease Related Deaths"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
library(glmnet)
```

```{r}
set.seed(7)
```

```{r}
#load data and clean data
death_df = read_csv("data/Vital_Statistics_Deaths_by_Region_and_Age-Group_by_Selected_Cause_of_Death___Beginning_2003.csv") %>% 
  janitor::clean_names() %>% 
  filter(selected_cause_of_death == "Diseases of the Heart",
         race_or_ethnicity != "Not Stated") %>%
  mutate(
    age_group = as.factor(age_group),
    age_group = fct_recode(
      age_group, "<1" = "1", "1-9" = "2", "10-19" = "3", "20-24" = "4", "25-34" = "5", "35-44"="6",                  "45-54" = "7", "55-64" = "8", "65-74" = "9", "75-84" = "10", "85+" = "11"),
    sex = as.factor(sex),
    sex = fct_recode(sex, "M" = "1", "F" = "2"),
    race_or_ethnicity = as.factor(race_or_ethnicity),
    race_or_ethnicity = fct_recode(race_or_ethnicity, "White Non Hispanic" = "1", 
                                   "Black Non Hispanic" = "2", "Hispanic" = "3", 
                                   "Other Non Hispanic" = "4")
    ) %>% 
  sample_n(200) %>% 
  select(deaths, sex, age_group, race_or_ethnicity)
```

```{r}
#fit a lasso model
x = model.matrix(deaths ~ ., death_df)[,-1] #create a matrix of predictors 
y = death_df$deaths #create outcome vector
```

```{r}
#fit model and cross validation
lambda = 10^(seq(3, -2, -0.1))

lasso_fit =
  glmnet(x, y, lambda = lambda)

lasso_cv =
  cv.glmnet(x, y, lambda = lambda)

lambda_opt = lasso_cv$lambda.min
```

```{r}
#plot lasso 
lasso_plot = broom::tidy(lasso_fit) %>% 
  select(term, lambda, estimate) %>% 
  complete(term, lambda, fill = list(estimate = 0) ) %>% 
  filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda, 10), y = estimate, group = term, color = term)) + 
  geom_path() + 
  geom_vline(xintercept = log(lambda_opt, 10), color = "blue", size = 1.2) +
  theme(legend.position = "none")

lasso_plot
```

```{r}
#Generate lasso result
lasso_fit = 
  glmnet(x, y, lambda = lambda_opt)

lasso_result = lasso_fit %>% broom::tidy()
```

```{r}
#run MLR model
MLR = lm(deaths ~ sex + age_group + race_or_ethnicity, data = death_df)

MLR_result = MLR %>% 
  broom::tidy() %>% 
  filter(p.value < 0.05) 

MLR_result
```

```{r}
#plot age_groups with heart disease related deaths
death_df %>% 
  ggplot(aes(y = deaths, x = reorder(age_group, deaths), color = age_group))+
  geom_boxplot()+
  theme_classic()+
  labs(x = "Age Groups",
       y = "Number of Deaths",
       title = "Number of Heart Disease Related Death with Age in NYC From 2003 to 2019")
```

```{r}
#plot race with heart disease related deaths
death_df %>% 
  ggplot(aes(y = deaths, x = reorder(race_or_ethnicity, deaths), color = race_or_ethnicity))+
  geom_boxplot()+
  theme_classic()+
  labs(x = "Race or Ethnicity",
       y = "Number of Deaths",
       title = "Number of Heart Disease Related Death with Race in NYC From 2003 to 2019")
```

```{r}
#plot sex with heart disease related deaths
death_df %>% 
  ggplot(aes(y = deaths, x = reorder(sex, deaths), color = sex))+
  geom_boxplot()+
  theme_classic()+
  labs(x = "Sex",
       y = "Number of Deaths",
       title = "Number of Heart Disease Related Death with Sex in NYC From 2003 to 2019")
```

